In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(5)
b = tf.constant(10)

In [4]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [5]:
l1 = tf.constant([5,10,15,20])
l2 = tf.constant([10,15,20,25])

In [7]:
print(l1+l2)

tf.Tensor([15 25 35 45], shape=(4,), dtype=int32)


In [8]:
l1-l2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-5, -5, -5, -5])>

In [9]:
l1*l2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 50, 150, 300, 500])>

In [10]:
l1/l2

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.5       , 0.66666667, 0.75      , 0.8       ])>

In [11]:
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 25, 35, 45])>

In [15]:
type((24))

int